services:
  webapi:
    image: alvarocar/citas-webapi:latest
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "8081:8081"
      - "8080:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:18.0-alpine
    environment:
      POSTGRES_DB: citasdb
      POSTGRES_USER: alvaro
      POSTGRES_PASSWORD: cardozo
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql

volumes:
  db_data:
